CREATE DATABASE IF NOT EXISTS saju;
USE saju;

CREATE TABLE IF NOT EXISTS logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    birth VARCHAR(20),
    hour VARCHAR(10),
    result TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 