plugin: aws_ec2
regions:
  - ap-northeast-2

filters:
  tag-key: Name

keyed_groups:
  - key: tags.Name
    prefix: ''
    separator: ''

hostnames:
  - tag:Name

compose:
  ansible_host: public_ip_address
  ansible_user: '"ubuntu"'
  ansible_ssh_private_key_file: '"/Users/junheo/.ssh/saju_app_key"'
